development:
   GEOIP_APP_KEY: 'PASTE APP ID HERE'
   STRIPE_SECRET_KEY: 'PASTE APP STRIPE SECRET KEY HERE'
   STRIPE_PUBLISHABLE_KEY: 'PASTE APP STRIPE PUBLISHABLE KEY HERE'
   STRIPE_CLIENT_ID: 'PASTE APP STRIPE CLIENT ID HERE'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-dev'
test:
   GEOIP_APP_KEY: 'PASTE APP ID HERE'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-test'
production:
   GEOIP_APP_KEY: 'PASTE APP ID HERE'
   STRIPE_SECRET_KEY: 'PASTE YOUR STRIPE SECRET KEY HERE'
   STRIPE_PUBLISHABLE_KEY: 'PASTE YOUR STRIPE PUBLISHABLE KEY HERE'
   STRIPE_CLIENT_ID: 'PASTE YOUR STRIPE CLIENT ID HERE'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-production'