development:
   GEOIP_APP_KEY: '305c1b131057225c92b577e07ced0e67c8c5280e64d12df1568af46dc95a62ae'
   STRIPE_SECRET_KEY: 'sk_test_BQokikJOvBiI2HlWgH4olfQ2'
   STRIPE_PUBLISHABLE_KEY: 'PASTE APP STRIPE PUBLISHABLE KEY HERE'
   STRIPE_CLIENT_ID: 'PASTE APP STRIPE CLIENT ID HERE'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-dev'
test:
   GEOIP_APP_KEY: '305c1b131057225c92b577e07ced0e67c8c5280e64d12df1568af46dc95a62ae'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-test'
production:
   GEOIP_APP_KEY: '305c1b131057225c92b577e07ced0e67c8c5280e64d12df1568af46dc95a62ae'
   STRIPE_SECRET_KEY: 'sk_test_BQokikJOvBiI2HlWgH4olfQ2'
   STRIPE_PUBLISHABLE_KEY: 'PASTE YOUR STRIPE PUBLISHABLE KEY HERE'
   STRIPE_CLIENT_ID: 'PASTE YOUR STRIPE CLIENT ID HERE'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-production'